### ISSUE TITLE
Is this really working?

### ISSUE THREAD

**Issue by mondsen** [jankais3r/Siri-NoLoggingPLS#2]
In the [Apple developer reference](https://developer.apple.com/business/documentation/Configuration-Profile-Reference.pdf) there is the information in the revision history that the key _allowSiriServerLogging_
was removed from the the Restrictions Payload.

So how can this work?

**Comment by jankais3r** [comment]
It might be deprecated in the future, but for now both iOS 13 and macOS Catalina still recognize this restriction. Many businesses and government agencies are actively using this restriction, so it might stay for that reason alone. But I agree, it would be nice if some publication could get Apple on record confirming that they are honoring this preference option.

**Comment by stultitiophobia** [comment]
It‘s also available in some MDM systems...

**Comment by mondsen** [comment]
OK thanks for the quick feedback. It is not very transparent from Apple how this is handled.
