### ISSUE TITLE
Do you think this is still necessary?

### ISSUE THREAD

**Issue by vowe** [jankais3r/Siri-NoLoggingPLS#3]
This policy seems to be deprecated. Apple now provides stronger privacy controls. 

![26D84438-BD16-432F-B000-48C913E5F1F5](https://user-images.githubusercontent.com/41863757/62185825-2fb4f280-b364-11e9-92df-a5292c64dd2b.jpeg)

Do you assume they are not working?

**Comment by jankais3r** [comment]
As Apple explains in their Siri Privacy Policy (picture below), the only "official" way to prevent voice samples from being stored is to completely disable Siri and dictation. The switch that you are talking about controls whether Siri metadata (i.e. what Siri learnt about you from the way you use your phone) gets analyzed or not. Clearly, Apple has no intention of letting people easily opt-out from the voice sample processing, and this Configurator restriction is there only for government agencies and business for which it would be a deal breaker.

![IMG_2068](https://user-images.githubusercontent.com/2159464/62190655-30548580-b372-11e9-9199-bd09c097ddee.jpeg)
