### ISSUE TITLE
No Allow server-side logging of Siri commands option in Apple Configurator 2

### ISSUE THREAD

**Issue by raspberryenvoie** [jankais3r/Siri-NoLoggingPLS#5]
Hi 
I'd like to create my own profile but I do not see any allow server-side logging of Siri commands option in Apple Configurator 2. Could you help me please ?
Thanks in advance

**Comment by raspberryenvoie** [comment]
![Screen Shot 2020-04-06 at 17 02 52](https://user-images.githubusercontent.com/61289832/78573014-7bd80100-7828-11ea-9217-7f4ab834369f.png)

**Comment by RayZopf** [comment]
seems Apple did listen and changed some stuff:
[cnbc news about it](https://www.cnbc.com/2019/10/28/ios-13point2-has-new-siri-privacy-settings-including-deletion-and-opt-out.html)

not that they excactly made it easy ....
[Apple support doc](https://support.apple.com/en-us/HT210657)

that might be the reason you cannot find it in latest configurator

**Comment by jankais3r** [comment]
As mentioned above, latest iOS releases have the option to disable this directly in Settings. For older iOS releases, use the profile from this repo or create your own with an old version of Configurator.
