### ISSUE TITLE
Is this still an issue?

### ISSUE THREAD

**Issue by mayurankv** [jankais3r/Siri-NoLoggingPLS#6]
I was just wondering if this was still an issue in ios14 and MacOS Big Sur as I've seen a few places saying this is included in default now. Would appreciate any clarification!

**Comment by jankais3r** [comment]
iOS 13.2 added a toggle in the Privacy settings that can be used to disable this. If you are using an older version of iOS, you still need the profile. Same goes for Big Sur.

![image](https://user-images.githubusercontent.com/2159464/102073863-35e62a80-3e04-11eb-80e2-033d4a88b496.png)
